server:
  port: 9528
spring:
  application:
    name: baishitong-dormitory-CMS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://175.178.1.83:3306/bst_dormitor_cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/bst_dormitor_cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.xiaowuyaya.bstdormitorycms.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    path: ~/.BST-dormitory/logs
    name: BST-dormitory.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 360